set_property SRC_FILE_INFO {cfile:C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/constrs_1/imports/Desktop/UltraZed-EV-CC-Master-XDC.xdc rfile:../../../fft_project.srcs/constrs_1/imports/Desktop/UltraZed-EV-CC-Master-XDC.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:406 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC8 [get_ports clk_p]
set_property src_info {type:XDC file:1 line:407 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC7 [get_ports clk_n]
set_property src_info {type:XDC file:1 line:412 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA13 [get_ports rstn]
set_property src_info {type:XDC file:1 line:416 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC14 [get_ports top_done]
