# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.runs/synth_1/fpga_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param power.BramSDPPropagationFix 1
set_param chipscope.maxJobs 4
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableLutRouteBelPower 1
set_param synth.incrementalSynthesisCache C:/Users/kccistc/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-23228-DESKTOP-7CFQ9ND/incrSyn
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu7ev-fbvb900-1-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.cache/wt [current_project]
set_property parent.project_path C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part avnet-tria:ultrazed_7ev_cc:part0:1.6 [current_project]
set_property ip_output_repo c:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib -sv {
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/BF2I.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/BF2I_1bundle.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/BF2I_2bundle.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/BF2I_4bundle.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/BF2I_8bundle.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/FFT_TOP.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/TOP_cbfp2.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/addr_gen_mod12.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/bit_shift.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/bit_shift_cbfp1.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/bit_shift_ctrl.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/cbfp0.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/cbfp1.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/cbfp2.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/cnt_1b_fsm.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/cnt_2b.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/cnt_3b_fsm.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/cnt_4b_fsm.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/cnt_5b.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/cos_in_gen.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/ctrl_mod0_fac8_0.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/ctrl_mod0_fac8_1.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/ctrl_mod1_fac8_0.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/ctrl_mod1_fac8_1.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/ctrl_mux_shift_reg.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/cu_cbfp0.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/cu_cbfp1.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/cu_mod0_0.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/cu_mod0_1.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/cu_mod0_2.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/cu_mod1_0.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/cu_mod1_1.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/cu_mod1_2.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/fac8_0_mod20.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/fac8_1_181j.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/fac8_1_m181j.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/fac8_1_mj.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/full_512_mem_ctrl.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/index_sum.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/mag_ctrl_cbfp0.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/mag_detect.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/mag_detect_cbf1.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/mem_cbfp0.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/mem_cbfp1.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/min_2in.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/min_4s_ctrl_cbfp0.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/min_8in_cbfp1.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/min_detect_16in.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/min_detect_4in.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/min_detect_cbfp1.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/min_fin_ctrl_cbfp0.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/mod0_0.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/mod0_1.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/mod0_2.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/mod1_0.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/mod1_1.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/mod1_2.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/mod2_0.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/mod2_1.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/mod2_2.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/module0.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/module1.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/module2.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/mul_fac8_0.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/mul_fac8_1.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/mul_fac8_1_mod11.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/mul_fac8_2.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/mul_fac8_2_mod12.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/mul_twf_ctrl.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/mux_32_to_16.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/mux_sel_cbfp0.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/mux_sel_ctrl_02.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/reorder.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/rom_twf_gen.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/saturate_16b.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/shift_reg.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/shift_reg16_mod11.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/shift_reg_cbfp.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/top_bit_shift.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/top_bit_shift_cbfp1.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/twf_rom_mod12.sv
  C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/imports/source/FPGA_TOP.sv
}
read_ip -quiet c:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet c:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/sources_1/ip/vio_1/vio_1.xci
set_property used_in_implementation false [get_files -all c:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.gen/sources_1/ip/vio_1/vio_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.gen/sources_1/ip/vio_1/vio_1_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/constrs_1/imports/Desktop/UltraZed-EV-CC-Master-XDC.xdc
set_property used_in_implementation false [get_files C:/Users/kccistc/Desktop/FPGA/fft_project/fft_project.srcs/constrs_1/imports/Desktop/UltraZed-EV-CC-Master-XDC.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top fpga_top -part xczu7ev-fbvb900-1-i
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef fpga_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file fpga_top_utilization_synth.rpt -pb fpga_top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
